### ISSUE TITLE
Fall 2017 Event - Preliminary Quality Review

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-hl2dm-freeplay#1]
- [x] Update MM / SM to latest
- [x] Make sure linux files are in `dist.linux` and that generic files are in `dist`
- [x] Verify advertisements works
- [x] Verify `sm_admin` works
- [x] Verify MOTD works
- [x] Verify your custom plugin is installed and working (dumps info to console on startup)
- [x] Verify LL config is loading
- [x] Verify map voting is enabled
- [x] Verify fast downloads are working

When testing use image name of `lacledeslan/gamesvr-hl2dm-freeplay` (`-srcds` and `:linux` are no longer necessary).

**Comment by JustinBenedick** [comment]
Updates sm/mm and sorted files aa2094e413df7c9156584a8f2c8a368500a6f3f2

**Comment by dudleycodes** [comment]
@JustinBenedick how's this going?

**Comment by JustinBenedick** [comment]
in game sm_admin works
